name: Terraform pipeline master

on:
  push:
    branches: ["master"]
env:
  AWS_REGION: "us-east-1"
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Chekout
      uses: actions/checkout@v1
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init
      run: terraform init
    
    - name: Terraform plan and apply dev
      run: |
        terraform workspace select dev
        terraform plan -input=false
        terraform apply --auto-approve -input=false
        
    - name: Terraform plan and apply stage
      run: |
        terraform workspace select stage
        terraform plan -input=false
        terraform apply --auto-approve -input=false
        
    - name: Terraform plan and apply prod
      run: |
        terraform workspace select prod
        terraform plan -input=false
        terraform apply --auto-approve -input=false
      
        
    